import React from "react";
import type { Metadata } from "next";
import "@styles/scss/main.scss";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}
        <Image src={'/whatsapp.png'} height={70} width={70} alt="" className="fixed right-[20px]"/>
      </body>
    </html>
  );
}
